//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FG_Madadjus
    {
        public int MadadjuId { get; set; }
        public Nullable<bool> MadadjuConfirm { get; set; }
        public Nullable<int> MadadjuCode { get; set; }
        public string MadadjuFName { get; set; }
        public string MadadjuLName { get; set; }
        public Nullable<int> MadadjuGen { get; set; }
        public Nullable<bool> MadadjuSiad { get; set; }
        public Nullable<int> MadadjuStatusId { get; set; }
        public string MadadjuBirthdate { get; set; }
        public string MadadjuBirthplace { get; set; }
        public string MadadjuPhone { get; set; }
        public string MadadjuMobile { get; set; }
        public string MadadjuNote { get; set; }
        public string MadadjuDetail { get; set; }
        public string MadadjuImage { get; set; }
        public string MadadjuImage1 { get; set; }
        public string MadadjuImage2 { get; set; }
        public string MadadjuImage3 { get; set; }
        public string MadadjuImage4 { get; set; }
        public string MadadjuImage5 { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string MadadjuSecurity { get; set; }
        public string MadadjuBirthCity { get; set; }
    }
}
