//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FG_MadadjusInfo2
    {
        public int MadadjuId { get; set; }
        public string MadadjuCode { get; set; }
        public string MadadjuFName { get; set; }
        public string MadadjuLName { get; set; }
        public string MadadjuFatherName { get; set; }
        public string MadadjuShnasnameh { get; set; }
        public string MadadjuCodemelli { get; set; }
        public string MadadjuBirthdate { get; set; }
        public string MadadjuBirthplace { get; set; }
        public string MadadjuPhone { get; set; }
        public string MadadjuMobile { get; set; }
        public string MadadjuAddress { get; set; }
        public Nullable<int> MadadjuFamilycount { get; set; }
        public string MadadjuDetail { get; set; }
        public Nullable<bool> MadadjuConfirm { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string MadadjuName { get; set; }
        public Nullable<int> MadadjuGen { get; set; }
        public Nullable<bool> MadadjuSiad { get; set; }
        public Nullable<int> MadadjuStatusId { get; set; }
        public Nullable<int> MadadjuParentStatusId { get; set; }
        public Nullable<int> MadadjuHomeStatusId { get; set; }
        public Nullable<System.DateTime> MadadjuLastAction { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string MadadjuGenTitle { get; set; }
        public string HomeStatusName { get; set; }
        public string MadadjuHomeStatus { get; set; }
        public string MadadjuParentStatus { get; set; }
        public string StatusName { get; set; }
        public string ParentStatusName { get; set; }
        public string PersonnelName { get; set; }
        public Nullable<int> PersonnelId { get; set; }
        public Nullable<int> MadadjuStatus { get; set; }
        public Nullable<decimal> MadadjuTotalPrice { get; set; }
        public Nullable<bool> MadadjuActive { get; set; }
    }
}
