//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSoftSharif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HamiEditSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HamiEditSet()
        {
            this.HamiMadadjouSet = new HashSet<HamiMadadjouSet>();
        }
    
        public int Id { get; set; }
        public int HamiId { get; set; }
        public string HamiFname { get; set; }
        public string NewHamiFname { get; set; }
        public string HamiLname { get; set; }
        public string NewHamiLname { get; set; }
        public string OldMobile1 { get; set; }
        public string NewMobile1 { get; set; }
        public string OldMobile2 { get; set; }
        public string NewMobile2 { get; set; }
        public string OldPhone1 { get; set; }
        public string NewPhone1 { get; set; }
        public string OldPhone2 { get; set; }
        public string NewPhone2 { get; set; }
        public string Email { get; set; }
        public string NationalCode { get; set; }
        public int MadadkarId { get; set; }
        public string MadadkarName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> DeleteOldMobile1 { get; set; }
        public Nullable<bool> DeleteOldMobile2 { get; set; }
        public Nullable<bool> DeleteOldPhone1 { get; set; }
        public Nullable<bool> DeleteOldPhone2 { get; set; }
        public Nullable<bool> TempSave { get; set; }
        public Nullable<bool> FinalSave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HamiMadadjouSet> HamiMadadjouSet { get; set; }
    }
}
